apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-db-noticias
spec:
  selector:
    matchLabels:
      app: db-noticias
  serviceName: svc-db-noticias
  replicas: 1
  template:
    metadata:
      labels:
        app: db-noticias
      name: db-noticias
    spec:
      containers:        
      - name: db-noticias-containers
        image: aluracursos/mysql-db:1
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
              name: configmap-db-noticias
        volumeMounts:
          - name: db
            mountPath: /var/lib/mysql
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db-pvc