apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - mountPath: /volume-dentro-do-container
        name: segundo-volume
    ports:
      - containerPort: 80
  - name: jenkins-container
    image: jenkins:2.60.3-alpine
    volumeMounts:
      - mountPath: /volume-dentro-do-container
        name: segundo-volume
    ports:
      - containerPort: 80
  volumes:
    - name: segundo-volume
      hostPath:
        # path: /run/desktop/mnt/host/c/Users/Leandro-Maximino/OneDrive/Alura/Cursos/Formacao_DevOps/Kubernetes_-_Deployments_Volumes_e_Escalabilidade/segundo-volume
        path: /c/Users/leand/OneDrive/Alura/Cursos/Formacao_DevOps/Kubernetes_-_Deployments_Volumes_e_Escalabilidade/segundo-volume
        type: DirectoryOrCreate